twig:
    default_path: '%kernel.project_dir%/templates'
    # globals: '%app.locales%'
    globals:
        locales: '%app.locales%'
        lang: 'App\Twig\LangExtension'

when@test:
    twig:
        strict_variables: true
