international:
    controller: App\Controller\InternationalController::index
    path:
        en: /
        fr: /accueil

country:
    controller: App\Controller\CountryController::index
    path: 
        en: /country/{slug}
        fr: /pays/{slug}

static:
    controller: App\Controller\StaticController::index
    path:
        en: /info/{slug}
        fr: /page/{slug}

contact:
    controller: App\Controller\ContactController::index
    path:
        en: /contact-us
        fr: /contactez-nous

register:
    controller: App\Controller\AdminSecuController::register
    path:
        en: /registration
        fr: /inscription

login:
  controller: App\Controller\AdminSecuController::login
  path:
    en: /login
    fr: /connexion

logout:
  controller: App\Controller\AdminSecuController::logout
  path:
    en: /logout
    fr: /deconnexion

product:
    controller: App\Controller\ProductController::index
    path:
        en: /product/{slug}
        fr: /produit/{slug}

order:
  controller: App\Controller\OrderController::index
  path:
    en: /order
    fr: /commande

payment:
  controller: App\Controller\PaymentController::index
  path:
    en: /payment
    fr: /paiement

admin:
  controller: App\Controller\AdminController::index
  path:
    en: /admin/dashbord
    fr: /admin/tableau

admin_country:
  controller: App\Controller\AdminCountryController::index
  path:
    en: /admin/country
    fr: /admin/pays

admin_country_edit:
  controller: App\Controller\AdminCountryController::register
  path:
    en: /admin/country/{id}
    fr: /admin/pays/{id}

admin_country_add:
  controller: App\Controller\AdminCountryController::register
  path:
    en: /admin/country/add
    fr: /admin/pays/ajout

admin_country_remove:
  controller: App\Controller\AdminCountryController::remove
  path:
    en: /admin/country/remove/{id}
    fr: /admin/pays/remove/{id}